name: e2e tests

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  test-setup-python:
    name: Test setup-python
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-20.04, windows-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run with setup-python 3.10
        id: cp310
        uses: ./
        with:
          python-version: '3.10'
      - name: Verify 3.10
        run: python __tests__/verify-python.py 3.10
      - name: Run python-path sample 3.10
        run: pipx run --python '${{ steps.cp310.outputs.python-path }}' nox --version

      - name: Run with setup-python ==3.8
        uses: ./
        with:
          python-version: '==3.10'
      - name: Verify ==3.8
        run: python __tests__/verify-python.py 3.10

      - name: Run with setup-python <3.11
        uses: ./
        with:
          python-version: '3.11'
      - name: Verify <3.11
        run: python __tests__/verify-python.py 3.11
